name: CI with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/raonigabriel/builder-java:latest
    
    steps:

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fix permissions
        run: |
              chmod 664 src/main/resources/db/migration/
              chmod +x src/main/resources/db/migration
              ls -la src/main/resources/db/migration

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            /root/.m2
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
